name: example
description: Example app for testing supafreeze
version: 1.0.0

environment:
  sdk: ^3.10.1

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  supafreeze:
    path: ../
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^6.0.0
  test: ^1.25.6
